apiVersion: apps/v1
kind: Deployment

metadata:
  name: fastpro

spec:
  replicas: 3

  selector:
    matchLabels:
      app: fastpro

  template:
    metadata:
      labels:
        app: fastpro

    spec:
      containers:
        - name: fastpro
          image: basanttimilsa8/fast-pro

          ports:
            - containerPort: 8000