apiVersion: apps/v1
kind: Deployment

metadata:
  name: fastpro

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fastpro

  template:
    metadata:
      labels:
        app: fastpro

    spec:
      containers:
        - name: fastpro
          image: basanttimilsa8/fast-pro:v7.0

          envFrom:
            - secretRef:
                name: fastpro-env

          ports:
            - containerPort: 8000
